---
title: Test Siteleaf
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  stores:
    title: Stores
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ar
    type: pages
  values:
    layout: default-ar
    author: ''
- scope:
    path: en
    type: pages
  values:
    layout: default-en
    author: ''
prod_url: test-forestry.meem.com.s3-website.ap-south-1.amazonaws.com
social-sitename-en: Meem Personal Banking
social-sitename-ar: الخدمات المصرفية الشخصية ميم
social-image-en: "/resources/images/twitter/seo_twitter_cover/slide1.png"
social-image-ar: "/resources/images/twitter/seo_twitter_cover/slide2.png"
sass:
  sass_dir: _sass
  style: compressed
exclude:
- html.iml
- meem dev.iml
- meem digital bank.iml
- webchat-form.html
- webchat-meem.js
- webchat-working.js
excerpt_separator: 
